# SPDX-FileCopyrightText: 2024 Citron Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: citron-android-canary-play-release

on:
  workflow_dispatch:
    inputs:
      release-track:
        description: 'Play store release track (internal/alpha/beta/production)'
        required: true
        default: 'alpha'

jobs:
  android:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Citron-Project/Cit' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.CI_RELEASE_TOKEN }}
      - run: npm install execa@5
      - uses: actions/github-script@v5
        name: 'Merge and publish Android Canary changes'
        env:
          CI_RELEASE_TOKEN: ${{ secrets.CI_RELEASE_TOKEN }}
          BUILD_CANARY: true
        with:
          script: |
            const execa = require("execa");
            const mergebot = require('./.github/workflows/android-merge.js').mergebot;
            process.chdir('${{ github.workspace }}');
            mergebot(github, context, execa);
      - name: Get tag name
        run: echo "GIT_TAG_NAME=$(cat tag-name.txt)" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache apksigner glslang-dev glslang-tools
      - name: Build
        run: ./.ci/scripts/android/canarybuild.sh
        env:
          CANARY_PLAY_ANDROID_KEYSTORE_B64: ${{ secrets.PLAY_ANDROID_KEYSTORE_B64 }}
          PLAY_ANDROID_KEY_ALIAS: ${{ secrets.PLAY_ANDROID_KEY_ALIAS }}
          PLAY_ANDROID_KEYSTORE_PASS: ${{ secrets.PLAY_ANDROID_KEYSTORE_PASS }}
          CANARY_SERVICE_ACCOUNT_KEY_B64: ${{ secrets.CANARY_SERVICE_ACCOUNT_KEY_B64 }}
          STORE_TRACK: ${{ github.event.inputs.release-track }}
          AUTO_VERSIONED: true
          BUILD_CANARY: true
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.CANARY_TAG_NAME }}
          name: ${{ env.CANARY_TAG_NAME }}
          draft: false
          prerelease: false
          repository: Citron-Project/citron-android
          token: ${{ secrets.CI_RELEASE_TOKEN }}
